import {
  Lead,
  Estimate,
  Job,
  RoomPrice,
  ExteriorPrice,
  Addon,
  VTO,
  ScorecardMetric,
  Rock,
  Todo,
  Issue,
  Seat,
  Meeting,
  DashboardKPIs,
  MonthlyKPI,
  BusinessSettings,
  TeamMember,
  Subcontractor,
  JobKPIs,
} from '@/types';

// Business Settings
export const mockBusinessSettings: BusinessSettings = {
  subPayoutPct: 60,
  subMaterialsPct: 15,
  subLaborPct: 45,
  minGrossProfitPerJob: 900,
  targetGrossMarginPct: 40,
  defaultDepositPct: 30,
  arTargetDays: 7,
  priceRoundingIncrement: 50,
};

// Team Members
export const mockTeamMembers: TeamMember[] = [
  {
    id: 'tm1',
    name: 'Rodrigo Campos',
    email: 'rodrigo@cmdpainting.com',
    phone: '(203) 555-0100',
    role: 'both',
    defaultCommissionPct: 5,
    isActive: true,
  },
  {
    id: 'tm2',
    name: 'Maria Garcia',
    email: 'maria@cmdpainting.com',
    phone: '(203) 555-0101',
    role: 'sales',
    defaultCommissionPct: 8,
    isActive: true,
  },
  {
    id: 'tm3',
    name: 'Carlos Rodriguez',
    email: 'carlos@cmdpainting.com',
    phone: '(203) 555-0102',
    role: 'pm',
    defaultCommissionPct: 5,
    isActive: true,
  },
  {
    id: 'tm4',
    name: 'Miguel Santos',
    email: 'miguel@cmdpainting.com',
    phone: '(203) 555-0103',
    role: 'pm',
    defaultCommissionPct: 5,
    isActive: true,
  },
];

// Subcontractors
export const mockSubcontractors: Subcontractor[] = [
  {
    id: 'sub1',
    name: 'Tony Vasquez',
    companyName: 'Vasquez Painting Crew',
    email: 'tony@vasquezpainting.com',
    phone: '(203) 555-0200',
    specialty: 'both',
    defaultPayoutPct: 60,
    isActive: true,
  },
  {
    id: 'sub2',
    name: 'Pedro Martinez',
    companyName: 'Martinez Interior Specialists',
    email: 'pedro@martinezpainting.com',
    phone: '(203) 555-0201',
    specialty: 'interior',
    defaultPayoutPct: 58,
    isActive: true,
  },
  {
    id: 'sub3',
    name: 'Juan Lopez',
    companyName: 'Lopez Exterior Pros',
    email: 'juan@lopezexterior.com',
    phone: '(203) 555-0202',
    specialty: 'exterior',
    defaultPayoutPct: 62,
    isActive: true,
  },
  {
    id: 'sub4',
    name: 'Roberto Silva',
    companyName: 'Silva Painting',
    email: 'roberto@silvapainting.com',
    phone: '(203) 555-0203',
    specialty: 'both',
    defaultPayoutPct: 60,
    isActive: true,
  },
];

// Leads
export const mockLeads: Lead[] = [
  {
    id: '1',
    firstName: 'John',
    lastName: 'Smith',
    email: 'john.smith@email.com',
    phone: '(203) 555-0101',
    address: '123 Oak Street',
    city: 'Greenwich',
    state: 'CT',
    zipCode: '06830',
    source: 'Google',
    status: 'estimate_scheduled',
    leadDate: '2024-12-10',
    nextFollowupDate: '2024-12-16',
    estimatedJobValue: 8500,
    projectType: 'interior',
    assignedTo: 'Maria Garcia',
  },
  {
    id: '2',
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.j@email.com',
    phone: '(203) 555-0102',
    address: '456 Maple Ave',
    city: 'Stamford',
    state: 'CT',
    zipCode: '06901',
    source: 'Referral',
    status: 'new',
    leadDate: '2024-12-14',
    estimatedJobValue: 12000,
    projectType: 'exterior',
  },
  {
    id: '3',
    firstName: 'Michael',
    lastName: 'Brown',
    email: 'mbrown@email.com',
    phone: '(203) 555-0103',
    address: '789 Elm Road',
    city: 'Norwalk',
    state: 'CT',
    zipCode: '06850',
    source: 'Thumbtack',
    status: 'estimated',
    leadDate: '2024-12-08',
    nextFollowupDate: '2024-12-17',
    estimatedJobValue: 5200,
    projectType: 'interior',
    assignedTo: 'Maria Garcia',
  },
  {
    id: '4',
    firstName: 'Emily',
    lastName: 'Davis',
    email: 'emily.d@email.com',
    phone: '(203) 555-0104',
    address: '321 Pine Lane',
    city: 'Westport',
    state: 'CT',
    zipCode: '06880',
    source: 'Website',
    status: 'won',
    leadDate: '2024-12-01',
    estimatedJobValue: 15000,
    projectType: 'both',
    assignedTo: 'Rodrigo Campos',
  },
  {
    id: '5',
    firstName: 'Robert',
    lastName: 'Wilson',
    email: 'rwilson@email.com',
    phone: '(203) 555-0105',
    address: '654 Cedar Blvd',
    city: 'Fairfield',
    state: 'CT',
    zipCode: '06824',
    source: 'Google',
    status: 'contacted',
    leadDate: '2024-12-12',
    nextFollowupDate: '2024-12-15',
    estimatedJobValue: 7800,
    projectType: 'interior',
  },
  {
    id: '6',
    firstName: 'Jennifer',
    lastName: 'Martinez',
    email: 'jmartinez@email.com',
    phone: '(203) 555-0106',
    address: '987 Birch Street',
    city: 'Darien',
    state: 'CT',
    zipCode: '06820',
    source: 'Referral',
    status: 'lost',
    leadDate: '2024-11-28',
    estimatedJobValue: 9500,
    projectType: 'exterior',
    wonLostReason: 'Chose competitor - lower price',
  },
];

// Jobs with enhanced commission/payment tracking
export const mockJobs: Job[] = [
  {
    id: '1',
    jobNumber: 'JOB-2024-001',
    clientName: 'Emily Davis',
    address: '321 Pine Lane',
    city: 'Westport',
    projectType: 'both',
    status: 'scheduled',
    jobDate: '2024-12-09',
    scheduledStartDate: '2024-12-09',
    scheduledEndDate: '2024-12-20',
    actualStartDate: '2024-12-09',
    jobValue: 15000,
    subMaterials: 2250,
    subLabor: 6750,
    subTotal: 9000,
    grossProfit: 6000,
    grossMarginPct: 40,
    // People
    salesRepId: 'tm1',
    salesRep: mockTeamMembers[0],
    projectManagerId: 'tm3',
    projectManager: mockTeamMembers[2],
    subcontractorId: 'sub1',
    subcontractor: mockSubcontractors[0],
    // Client Payments
    depositRequired: 4500,
    depositPaid: true,
    jobPaid: false,
    balanceDue: 10500,
    // Sales Commission
    salesCommissionPct: 5,
    salesCommissionAmount: 750,
    salesCommissionPaid: false,
    // PM Commission
    pmCommissionPct: 5,
    pmCommissionAmount: 750,
    pmCommissionPaid: false,
    // Subcontractor
    subcontractorPrice: 9000,
    subcontractorPaid: false,
    // Flags
    meetsMinGp: true,
    meetsTargetGm: true,
    profitFlag: 'OK',
    crewLeader: 'Carlos Rodriguez',
    invoiceAmount: 15000,
  },
  {
    id: '2',
    jobNumber: 'JOB-2024-002',
    clientName: 'Amanda Chen',
    address: '555 Harbor View',
    city: 'Greenwich',
    projectType: 'interior',
    status: 'got_the_job',
    jobDate: '2024-12-15',
    scheduledStartDate: '2024-12-23',
    scheduledEndDate: '2024-12-27',
    jobValue: 8500,
    subMaterials: 1275,
    subLabor: 3825,
    subTotal: 5100,
    grossProfit: 3400,
    grossMarginPct: 40,
    // People
    salesRepId: 'tm2',
    salesRep: mockTeamMembers[1],
    projectManagerId: 'tm3',
    projectManager: mockTeamMembers[2],
    subcontractorId: 'sub2',
    subcontractor: mockSubcontractors[1],
    // Client Payments
    depositRequired: 2550,
    depositPaid: false,
    jobPaid: false,
    balanceDue: 8500,
    // Sales Commission
    salesCommissionPct: 8,
    salesCommissionAmount: 680,
    salesCommissionPaid: false,
    // PM Commission
    pmCommissionPct: 5,
    pmCommissionAmount: 425,
    pmCommissionPaid: false,
    // Subcontractor
    subcontractorPrice: 4930, // 58% for this sub
    subcontractorPaid: false,
    // Flags
    meetsMinGp: true,
    meetsTargetGm: true,
    profitFlag: 'OK',
    crewLeader: 'Carlos Rodriguez',
    invoiceAmount: 8500,
  },
  {
    id: '3',
    jobNumber: 'JOB-2024-003',
    clientName: 'David Thompson',
    address: '222 Beach Road',
    city: 'Stamford',
    projectType: 'exterior',
    status: 'completed',
    jobDate: '2024-12-02',
    scheduledStartDate: '2024-12-02',
    scheduledEndDate: '2024-12-06',
    actualStartDate: '2024-12-02',
    actualEndDate: '2024-12-06',
    jobValue: 12000,
    subMaterials: 1800,
    subLabor: 5400,
    subTotal: 7200,
    grossProfit: 4800,
    grossMarginPct: 40,
    // People
    salesRepId: 'tm1',
    salesRep: mockTeamMembers[0],
    projectManagerId: 'tm4',
    projectManager: mockTeamMembers[3],
    subcontractorId: 'sub3',
    subcontractor: mockSubcontractors[2],
    // Client Payments
    depositRequired: 3600,
    depositPaid: true,
    jobPaid: true,
    balanceDue: 0,
    invoiceDate: '2024-12-06',
    paymentReceivedDate: '2024-12-10',
    daysToCollect: 4,
    // Sales Commission
    salesCommissionPct: 5,
    salesCommissionAmount: 600,
    salesCommissionPaid: true,
    // PM Commission
    pmCommissionPct: 5,
    pmCommissionAmount: 600,
    pmCommissionPaid: true,
    // Subcontractor
    subcontractorPrice: 7440, // 62% for exterior sub
    subcontractorPaid: true,
    // Flags
    meetsMinGp: true,
    meetsTargetGm: true,
    profitFlag: 'OK',
    crewLeader: 'Miguel Santos',
    invoiceAmount: 12000,
  },
  {
    id: '4',
    jobNumber: 'JOB-2024-004',
    clientName: 'Lisa Anderson',
    address: '888 Sunset Drive',
    city: 'New Canaan',
    projectType: 'interior',
    status: 'completed',
    jobDate: '2024-11-25',
    scheduledStartDate: '2024-11-25',
    scheduledEndDate: '2024-11-29',
    actualStartDate: '2024-11-25',
    actualEndDate: '2024-11-29',
    jobValue: 6500,
    subMaterials: 975,
    subLabor: 2925,
    subTotal: 3900,
    grossProfit: 2600,
    grossMarginPct: 40,
    // People
    salesRepId: 'tm2',
    salesRep: mockTeamMembers[1],
    projectManagerId: 'tm3',
    projectManager: mockTeamMembers[2],
    subcontractorId: 'sub2',
    subcontractor: mockSubcontractors[1],
    // Client Payments
    depositRequired: 1950,
    depositPaid: true,
    jobPaid: true,
    balanceDue: 0,
    invoiceDate: '2024-11-29',
    paymentReceivedDate: '2024-12-03',
    daysToCollect: 4,
    // Sales Commission
    salesCommissionPct: 8,
    salesCommissionAmount: 520,
    salesCommissionPaid: true,
    // PM Commission
    pmCommissionPct: 5,
    pmCommissionAmount: 325,
    pmCommissionPaid: false,
    // Subcontractor
    subcontractorPrice: 3770, // 58%
    subcontractorPaid: true,
    // Flags
    meetsMinGp: true,
    meetsTargetGm: true,
    profitFlag: 'OK',
    crewLeader: 'Carlos Rodriguez',
    invoiceAmount: 6500,
  },
  {
    id: '5',
    jobNumber: 'JOB-2024-005',
    clientName: 'Mark Williams',
    address: '444 River Road',
    city: 'Norwalk',
    projectType: 'interior',
    status: 'completed',
    jobDate: '2024-12-05',
    scheduledStartDate: '2024-12-05',
    scheduledEndDate: '2024-12-08',
    actualStartDate: '2024-12-05',
    actualEndDate: '2024-12-08',
    jobValue: 2200,
    subMaterials: 330,
    subLabor: 990,
    subTotal: 1320,
    grossProfit: 880,
    grossMarginPct: 40,
    // People
    salesRepId: 'tm1',
    salesRep: mockTeamMembers[0],
    projectManagerId: 'tm4',
    projectManager: mockTeamMembers[3],
    subcontractorId: 'sub4',
    subcontractor: mockSubcontractors[3],
    // Client Payments
    depositRequired: 660,
    depositPaid: true,
    jobPaid: false,
    balanceDue: 1540,
    invoiceDate: '2024-12-08',
    // Sales Commission
    salesCommissionPct: 5,
    salesCommissionAmount: 110,
    salesCommissionPaid: false,
    // PM Commission
    pmCommissionPct: 5,
    pmCommissionAmount: 110,
    pmCommissionPaid: false,
    // Subcontractor
    subcontractorPrice: 1320,
    subcontractorPaid: false,
    // Flags
    meetsMinGp: false,
    meetsTargetGm: true,
    profitFlag: 'RAISE PRICE',
    crewLeader: 'Miguel Santos',
    invoiceAmount: 2200,
  },
  {
    id: '6',
    jobNumber: 'JOB-2024-006',
    clientName: 'Sarah Johnson',
    address: '789 Oak Avenue',
    city: 'Darien',
    projectType: 'exterior',
    status: 'lead',
    jobDate: '2024-12-14',
    scheduledStartDate: '2025-01-06',
    scheduledEndDate: '2025-01-10',
    jobValue: 18500,
    subMaterials: 2775,
    subLabor: 8325,
    subTotal: 11100,
    grossProfit: 7400,
    grossMarginPct: 40,
    // People
    salesRepId: 'tm2',
    salesRep: mockTeamMembers[1],
    projectManagerId: 'tm3',
    projectManager: mockTeamMembers[2],
    subcontractorId: 'sub1',
    subcontractor: mockSubcontractors[0],
    // Client Payments
    depositRequired: 5550,
    depositPaid: false,
    jobPaid: false,
    balanceDue: 18500,
    // Sales Commission
    salesCommissionPct: 8,
    salesCommissionAmount: 1480,
    salesCommissionPaid: false,
    // PM Commission
    pmCommissionPct: 5,
    pmCommissionAmount: 925,
    pmCommissionPaid: false,
    // Subcontractor
    subcontractorPrice: 11100,
    subcontractorPaid: false,
    // Flags
    meetsMinGp: true,
    meetsTargetGm: true,
    profitFlag: 'OK',
    crewLeader: 'Carlos Rodriguez',
    invoiceAmount: 18500,
  },
  {
    id: '7',
    jobNumber: 'JOB-2024-007',
    clientName: 'Robert Chen',
    address: '123 Maple Street',
    city: 'Greenwich',
    projectType: 'interior',
    status: 'completed',
    jobDate: '2024-11-15',
    scheduledStartDate: '2024-11-15',
    scheduledEndDate: '2024-11-20',
    actualStartDate: '2024-11-15',
    actualEndDate: '2024-11-20',
    jobValue: 9800,
    subMaterials: 1470,
    subLabor: 4410,
    subTotal: 5880,
    grossProfit: 3920,
    grossMarginPct: 40,
    // People
    salesRepId: 'tm1',
    salesRep: mockTeamMembers[0],
    projectManagerId: 'tm4',
    projectManager: mockTeamMembers[3],
    subcontractorId: 'sub2',
    subcontractor: mockSubcontractors[1],
    // Client Payments
    depositRequired: 2940,
    depositPaid: true,
    jobPaid: true,
    balanceDue: 0,
    invoiceDate: '2024-11-20',
    paymentReceivedDate: '2024-11-25',
    daysToCollect: 5,
    // Sales Commission
    salesCommissionPct: 5,
    salesCommissionAmount: 490,
    salesCommissionPaid: true,
    // PM Commission
    pmCommissionPct: 5,
    pmCommissionAmount: 490,
    pmCommissionPaid: true,
    // Subcontractor
    subcontractorPrice: 5684, // 58%
    subcontractorPaid: true,
    // Flags
    meetsMinGp: true,
    meetsTargetGm: true,
    profitFlag: 'OK',
    crewLeader: 'Miguel Santos',
    invoiceAmount: 9800,
  },
  {
    id: '8',
    jobNumber: 'JOB-2024-008',
    clientName: 'Jennifer Martinez',
    address: '456 Beach Road',
    city: 'Westport',
    projectType: 'both',
    status: 'scheduled',
    jobDate: '2024-12-12',
    scheduledStartDate: '2024-12-18',
    scheduledEndDate: '2024-12-22',
    jobValue: 22000,
    subMaterials: 3300,
    subLabor: 9900,
    subTotal: 13200,
    grossProfit: 8800,
    grossMarginPct: 40,
    // People
    salesRepId: 'tm2',
    salesRep: mockTeamMembers[1],
    projectManagerId: 'tm3',
    projectManager: mockTeamMembers[2],
    subcontractorId: 'sub1',
    subcontractor: mockSubcontractors[0],
    // Client Payments
    depositRequired: 6600,
    depositPaid: true,
    jobPaid: false,
    balanceDue: 15400,
    // Sales Commission
    salesCommissionPct: 8,
    salesCommissionAmount: 1760,
    salesCommissionPaid: false,
    // PM Commission
    pmCommissionPct: 5,
    pmCommissionAmount: 1100,
    pmCommissionPaid: false,
    // Subcontractor
    subcontractorPrice: 13200,
    subcontractorPaid: false,
    // Flags
    meetsMinGp: true,
    meetsTargetGm: true,
    profitFlag: 'OK',
    crewLeader: 'Carlos Rodriguez',
    invoiceAmount: 22000,
  },
];

// Calculate Job KPIs helper function
export function calculateJobKPIs(jobs: Job[]): JobKPIs {
  const totalJobValue = jobs.reduce((sum: any, job: any) => sum + job.jobValue, 0);
  const totalGrossProfit = jobs.reduce((sum: any, job: any) => sum + job.grossProfit, 0);

  const salesCommissionsPending = jobs
    .filter((job: any) => !job.salesCommissionPaid)
    .reduce((sum: any, job: any) => sum + job.salesCommissionAmount, 0);

  const salesCommissionsPaid = jobs
    .filter((job: any) => job.salesCommissionPaid)
    .reduce((sum: any, job: any) => sum + job.salesCommissionAmount, 0);

  const pmCommissionsPending = jobs
    .filter((job: any) => !job.pmCommissionPaid)
    .reduce((sum: any, job: any) => sum + job.pmCommissionAmount, 0);

  const pmCommissionsPaid = jobs
    .filter((job: any) => job.pmCommissionPaid)
    .reduce((sum: any, job: any) => sum + job.pmCommissionAmount, 0);

  const subcontractorPending = jobs
    .filter((job: any) => !job.subcontractorPaid)
    .reduce((sum: any, job: any) => sum + job.subcontractorPrice, 0);

  const subcontractorPaid = jobs
    .filter((job: any) => job.subcontractorPaid)
    .reduce((sum: any, job: any) => sum + job.subcontractorPrice, 0);

  return {
    totalJobValue,
    averageJobValue: jobs.length > 0 ? totalJobValue / jobs.length : 0,
    jobCount: jobs.length,
    totalGrossProfit,
    salesCommissionsPending,
    salesCommissionsPaid,
    pmCommissionsPending,
    pmCommissionsPaid,
    subcontractorPending,
    subcontractorPaid,
  };
}

// Room Prices (Interior Price Book)
export const mockRoomPrices: RoomPrice[] = [
  { id: '1', roomType: 'Bedroom', size: 'Small', typicalSqft: 100, wallsOnly: 650, wallsTrim: 850, wallsTrimCeiling: 1050, fullRefresh: 1300 },
  { id: '2', roomType: 'Bedroom', size: 'Medium', typicalSqft: 150, wallsOnly: 950, wallsTrim: 1200, wallsTrimCeiling: 1500, fullRefresh: 1850 },
  { id: '3', roomType: 'Bedroom', size: 'Large', typicalSqft: 200, wallsOnly: 1300, wallsTrim: 1600, wallsTrimCeiling: 2000, fullRefresh: 2450 },
  { id: '4', roomType: 'Bedroom', size: 'Master', typicalSqft: 300, wallsOnly: 1950, wallsTrim: 2400, wallsTrimCeiling: 3000, fullRefresh: 3650 },
  { id: '5', roomType: 'Bathroom', size: 'Small', typicalSqft: 50, wallsOnly: 450, wallsTrim: 600, wallsTrimCeiling: 750, fullRefresh: 950 },
  { id: '6', roomType: 'Bathroom', size: 'Medium', typicalSqft: 80, wallsOnly: 550, wallsTrim: 750, wallsTrimCeiling: 950, fullRefresh: 1200 },
  { id: '7', roomType: 'Bathroom', size: 'Large/Master', typicalSqft: 120, wallsOnly: 800, wallsTrim: 1050, wallsTrimCeiling: 1300, fullRefresh: 1600 },
  { id: '8', roomType: 'Kitchen', size: 'Small', typicalSqft: 100, wallsOnly: 700, wallsTrim: 950, wallsTrimCeiling: 1200, fullRefresh: 1500 },
  { id: '9', roomType: 'Kitchen', size: 'Medium', typicalSqft: 150, wallsOnly: 1000, wallsTrim: 1350, wallsTrimCeiling: 1700, fullRefresh: 2100 },
  { id: '10', roomType: 'Kitchen', size: 'Large', typicalSqft: 200, wallsOnly: 1350, wallsTrim: 1800, wallsTrimCeiling: 2250, fullRefresh: 2800 },
  { id: '11', roomType: 'Living Room', size: 'Small', typicalSqft: 150, wallsOnly: 950, wallsTrim: 1250, wallsTrimCeiling: 1550, fullRefresh: 1900 },
  { id: '12', roomType: 'Living Room', size: 'Medium', typicalSqft: 250, wallsOnly: 1600, wallsTrim: 2100, wallsTrimCeiling: 2600, fullRefresh: 3200 },
  { id: '13', roomType: 'Living Room', size: 'Large', typicalSqft: 400, wallsOnly: 2600, wallsTrim: 3400, wallsTrimCeiling: 4200, fullRefresh: 5150 },
  { id: '14', roomType: 'Dining Room', size: 'Small', typicalSqft: 100, wallsOnly: 650, wallsTrim: 850, wallsTrimCeiling: 1050, fullRefresh: 1300 },
  { id: '15', roomType: 'Dining Room', size: 'Medium', typicalSqft: 150, wallsOnly: 950, wallsTrim: 1250, wallsTrimCeiling: 1550, fullRefresh: 1900 },
  { id: '16', roomType: 'Hallway', size: 'Small', typicalSqft: 50, wallsOnly: 350, wallsTrim: 500, wallsTrimCeiling: 650, fullRefresh: 850 },
  { id: '17', roomType: 'Hallway', size: 'Long', typicalSqft: 100, wallsOnly: 650, wallsTrim: 900, wallsTrimCeiling: 1150, fullRefresh: 1450 },
  { id: '18', roomType: 'Stairway', size: 'Standard', typicalSqft: 150, wallsOnly: 1200, wallsTrim: 1600, wallsTrimCeiling: 2000, fullRefresh: 2500 },
];

// Exterior Prices
export const mockExteriorPrices: ExteriorPrice[] = [
  { id: '1', surfaceType: 'Wood Siding', pricePerSqft: 3.50, prepMultiplier: 1.0 },
  { id: '2', surfaceType: 'High-End Wood', pricePerSqft: 5.00, prepMultiplier: 1.2 },
  { id: '3', surfaceType: 'Vinyl Siding', pricePerSqft: 2.75, prepMultiplier: 1.0 },
  { id: '4', surfaceType: 'Brick', pricePerSqft: 5.00, prepMultiplier: 1.0 },
  { id: '5', surfaceType: 'Stucco', pricePerSqft: 3.25, prepMultiplier: 1.0 },
  { id: '6', surfaceType: 'Metal', pricePerSqft: 3.25, prepMultiplier: 1.0 },
  { id: '7', surfaceType: 'Lead Paint', pricePerSqft: 5.50, prepMultiplier: 1.5 },
  { id: '8', surfaceType: 'Deck Stain', pricePerSqft: 6.50, prepMultiplier: 1.0 },
];

// Add-ons
export const mockAddons: Addon[] = [
  { id: '1', name: 'Closet (Reach-in) - Walls Only', category: 'interior', unit: 'each', basePrice: 150 },
  { id: '2', name: 'Closet (Reach-in) - Walls + Trim/Shelves', category: 'interior', unit: 'each', basePrice: 250 },
  { id: '3', name: 'Closet (Walk-in) - Walls Only', category: 'interior', unit: 'each', basePrice: 300 },
  { id: '4', name: 'Closet (Walk-in) - Walls + Trim/Shelves', category: 'interior', unit: 'each', basePrice: 450 },
  { id: '5', name: 'Door - One Side', category: 'interior', unit: 'each', basePrice: 75 },
  { id: '6', name: 'Door - Both Sides', category: 'interior', unit: 'each', basePrice: 125 },
  { id: '7', name: 'Door Frame/Casing', category: 'interior', unit: 'each', basePrice: 50 },
  { id: '8', name: 'Window Sash', category: 'interior', unit: 'each', basePrice: 45 },
  { id: '9', name: 'Window Trim', category: 'interior', unit: 'each', basePrice: 35 },
  { id: '10', name: 'Baseboard', category: 'interior', unit: 'linear_ft', basePrice: 2.50 },
  { id: '11', name: 'Crown Molding', category: 'interior', unit: 'linear_ft', basePrice: 4.00 },
  { id: '12', name: 'Built-in Shelves', category: 'interior', unit: 'linear_ft', basePrice: 8.00 },
  { id: '13', name: 'Extra Coat', category: 'both', unit: 'per_room', basePrice: 150 },
  { id: '14', name: 'Minor Drywall Repair', category: 'interior', unit: 'each', basePrice: 50 },
  { id: '15', name: 'Exterior Trim', category: 'exterior', unit: 'linear_ft', basePrice: 3.50 },
  { id: '16', name: 'Shutters', category: 'exterior', unit: 'each', basePrice: 45 },
];

// V/TO
export const mockVTO: VTO = {
  coreValues: [
    'Quality First - We never cut corners',
    'On-Time Every Time - Reliability builds trust',
    'Respect the Home - Treat every property like our own',
    'Clear Communication - No surprises',
    'Team Excellence - We win together',
  ],
  coreFocusPurpose: 'Transform homes and create lasting impressions through exceptional painting craftsmanship',
  coreFocusNiche: 'Premium residential painting services in Fairfield County, CT',
  tenYearTarget: '$20M annual revenue, #1 residential painter in CT, 50+ full-time employees',
  threeYearRevenue: 10000000,
  threeYearProfit: 2000000,
  threeYearPicture: '3 dedicated crews, 2 office staff, systemized operations, 500+ jobs/year, 45% gross margin, recognized brand in Fairfield County',
  oneYearRevenue: 5000000,
  oneYearProfit: 1000000,
  oneYearGoals: [
    'Hit $5M revenue',
    'Maintain 40% gross margin on all jobs',
    'Hire 2 additional crew leaders',
    'Launch new website with online booking',
    'Implement CRM and job tracking system',
    'Establish partnerships with 5 interior designers',
    'Achieve 50+ 5-star Google reviews',
  ],
  targetMarket: 'Homeowners in Fairfield County, CT with homes valued $500K-$3M, ages 35-65, who value quality over price',
  threeUniques: [
    'Premium finish guarantee - We fix any imperfections for 2 years',
    'Clean site promise - Your home is cleaner when we leave',
    'On-time or its free - We hit our deadlines or give 10% discount',
  ],
  provenProcess: '1. Free Consultation → 2. Detailed Estimate → 3. Color Selection Support → 4. Prep & Protect → 5. Expert Application → 6. Final Walkthrough → 7. 2-Year Guarantee',
  guarantee: 'If you\'re not 100% satisfied with our work, we\'ll redo it at no cost. Plus, our 2-year warranty covers any peeling, cracking, or fading.',
  longTermIssues: [
    'Need to develop crew leader training program',
    'Consider expanding to commercial market',
    'Evaluate franchise model for growth',
    'Build relationships with real estate agents',
  ],
};

// Scorecard Metrics
export const mockScorecardMetrics: ScorecardMetric[] = [
  {
    id: '1',
    name: 'Leads Generated',
    owner: 'Maria Garcia',
    goalValue: 25,
    goalType: 'number',
    goalDirection: 'above',
    category: 'leading',
    entries: [
      { weekEndingDate: '2024-12-15', actualValue: 28, onTrack: true },
      { weekEndingDate: '2024-12-08', actualValue: 22, onTrack: false },
      { weekEndingDate: '2024-12-01', actualValue: 30, onTrack: true },
      { weekEndingDate: '2024-11-24', actualValue: 26, onTrack: true },
    ],
  },
  {
    id: '2',
    name: 'Estimates Sent',
    owner: 'Rodrigo Campos',
    goalValue: 15,
    goalType: 'number',
    goalDirection: 'above',
    category: 'leading',
    entries: [
      { weekEndingDate: '2024-12-15', actualValue: 18, onTrack: true },
      { weekEndingDate: '2024-12-08', actualValue: 14, onTrack: false },
      { weekEndingDate: '2024-12-01', actualValue: 16, onTrack: true },
      { weekEndingDate: '2024-11-24', actualValue: 15, onTrack: true },
    ],
  },
  {
    id: '3',
    name: 'Close Rate',
    owner: 'Rodrigo Campos',
    goalValue: 40,
    goalType: 'percent',
    goalDirection: 'above',
    category: 'leading',
    entries: [
      { weekEndingDate: '2024-12-15', actualValue: 45, onTrack: true },
      { weekEndingDate: '2024-12-08', actualValue: 38, onTrack: false },
      { weekEndingDate: '2024-12-01', actualValue: 42, onTrack: true },
      { weekEndingDate: '2024-11-24', actualValue: 44, onTrack: true },
    ],
  },
  {
    id: '4',
    name: 'Weekly Revenue',
    owner: 'Rodrigo Campos',
    goalValue: 100000,
    goalType: 'currency',
    goalDirection: 'above',
    category: 'lagging',
    entries: [
      { weekEndingDate: '2024-12-15', actualValue: 112000, onTrack: true },
      { weekEndingDate: '2024-12-08', actualValue: 89000, onTrack: false },
      { weekEndingDate: '2024-12-01', actualValue: 105000, onTrack: true },
      { weekEndingDate: '2024-11-24', actualValue: 98000, onTrack: false },
    ],
  },
  {
    id: '5',
    name: 'Jobs Completed',
    owner: 'Carlos Rodriguez',
    goalValue: 8,
    goalType: 'number',
    goalDirection: 'above',
    category: 'lagging',
    entries: [
      { weekEndingDate: '2024-12-15', actualValue: 9, onTrack: true },
      { weekEndingDate: '2024-12-08', actualValue: 7, onTrack: false },
      { weekEndingDate: '2024-12-01', actualValue: 8, onTrack: true },
      { weekEndingDate: '2024-11-24', actualValue: 10, onTrack: true },
    ],
  },
  {
    id: '6',
    name: 'Gross Margin %',
    owner: 'Rodrigo Campos',
    goalValue: 40,
    goalType: 'percent',
    goalDirection: 'above',
    category: 'lagging',
    entries: [
      { weekEndingDate: '2024-12-15', actualValue: 41, onTrack: true },
      { weekEndingDate: '2024-12-08', actualValue: 39, onTrack: false },
      { weekEndingDate: '2024-12-01', actualValue: 42, onTrack: true },
      { weekEndingDate: '2024-11-24', actualValue: 40, onTrack: true },
    ],
  },
];

// Rocks
export const mockRocks: Rock[] = [
  { id: '1', title: 'Launch new CRM system', description: 'Implement and train team on new customer management system', owner: 'Rodrigo Campos', rockType: 'company', quarter: 4, year: 2024, status: 'on_track', dueDate: '2024-12-31' },
  { id: '2', title: 'Hire 2 crew leaders', description: 'Recruit and onboard two experienced crew leaders', owner: 'Rodrigo Campos', rockType: 'company', quarter: 4, year: 2024, status: 'off_track', dueDate: '2024-12-31' },
  { id: '3', title: 'Hit $1.2M Q4 revenue', description: 'Close and complete enough jobs to reach quarterly revenue target', owner: 'Rodrigo Campos', rockType: 'company', quarter: 4, year: 2024, status: 'on_track', dueDate: '2024-12-31' },
  { id: '4', title: 'Get 15 new Google reviews', description: 'Implement review request process, target 5-star reviews', owner: 'Maria Garcia', rockType: 'individual', quarter: 4, year: 2024, status: 'on_track', dueDate: '2024-12-31' },
  { id: '5', title: 'Complete estimator training', description: 'Master the new estimating system and pricing matrix', owner: 'Maria Garcia', rockType: 'individual', quarter: 4, year: 2024, status: 'complete', dueDate: '2024-12-15' },
  { id: '6', title: 'Reduce callback rate to <2%', description: 'Improve quality control to minimize post-job callbacks', owner: 'Carlos Rodriguez', rockType: 'individual', quarter: 4, year: 2024, status: 'on_track', dueDate: '2024-12-31' },
];

// Todos
export const mockTodos: Todo[] = [
  { id: '1', title: 'Follow up with John Smith estimate', owner: 'Maria Garcia', dueDate: '2024-12-16', status: 'pending', createdAt: '2024-12-09' },
  { id: '2', title: 'Order paint for Davis job', owner: 'Carlos Rodriguez', dueDate: '2024-12-15', status: 'done', createdAt: '2024-12-08' },
  { id: '3', title: 'Schedule walk-through with Chen', owner: 'Rodrigo Campos', dueDate: '2024-12-17', status: 'pending', createdAt: '2024-12-10' },
  { id: '4', title: 'Send invoice to Thompson', owner: 'Maria Garcia', dueDate: '2024-12-15', status: 'pending', createdAt: '2024-12-06' },
  { id: '5', title: 'Review Indeed applicants', owner: 'Rodrigo Campos', dueDate: '2024-12-18', status: 'pending', createdAt: '2024-12-12' },
  { id: '6', title: 'Update price book for Q1', owner: 'Rodrigo Campos', dueDate: '2024-12-20', status: 'pending', createdAt: '2024-12-10' },
  { id: '7', title: 'Call back Robert Wilson', owner: 'Maria Garcia', dueDate: '2024-12-15', status: 'pending', createdAt: '2024-12-12' },
];

// Issues
export const mockIssues: Issue[] = [
  { id: '1', title: 'Paint supplier raised prices 8%', description: 'Need to evaluate alternative suppliers or adjust pricing', issueType: 'short_term', priority: 1, status: 'open', createdBy: 'Rodrigo Campos', createdAt: '2024-12-10' },
  { id: '2', title: 'Crew leader Carlos needs assistant', description: 'Jobs taking longer than estimated, need additional help', issueType: 'short_term', priority: 2, status: 'in_discussion', createdBy: 'Carlos Rodriguez', createdAt: '2024-12-08' },
  { id: '3', title: 'Vehicle maintenance schedule', description: 'Need to establish regular maintenance routine for trucks', issueType: 'short_term', priority: 3, status: 'open', createdBy: 'Carlos Rodriguez', createdAt: '2024-12-05' },
  { id: '4', title: 'Consider expanding to Westchester NY', description: 'Received multiple inquiries from NY clients', issueType: 'long_term', priority: 2, status: 'open', createdBy: 'Rodrigo Campos', createdAt: '2024-11-15' },
  { id: '5', title: 'Develop apprentice program', description: 'Create training program for new painters', issueType: 'long_term', priority: 3, status: 'open', createdBy: 'Rodrigo Campos', createdAt: '2024-10-20' },
];

// Accountability Chart
export const mockSeats: Seat[] = [
  {
    id: '1',
    seatName: 'Owner/Integrator',
    roleDescription: 'Runs the business day-to-day, integrates all functions',
    responsibilities: ['Financial management', 'Sales & estimating', 'Team leadership', 'Customer relationships', 'Strategic planning'],
    personName: 'Rodrigo Campos',
    personId: 'p1',
    gwcGetsIt: true,
    gwcWantsIt: true,
    gwcCapacity: true,
    isRightPersonRightSeat: true,
  },
  {
    id: '2',
    seatName: 'Office Manager',
    roleDescription: 'Manages leads, scheduling, and customer communication',
    responsibilities: ['Lead management', 'Scheduling', 'Customer follow-up', 'Invoicing', 'Admin support'],
    personName: 'Maria Garcia',
    personId: 'p2',
    reportsToId: '1',
    gwcGetsIt: true,
    gwcWantsIt: true,
    gwcCapacity: true,
    isRightPersonRightSeat: true,
  },
  {
    id: '3',
    seatName: 'Crew Leader - Team A',
    roleDescription: 'Leads painting crew, ensures quality and timeline',
    responsibilities: ['Job site management', 'Quality control', 'Crew supervision', 'Material management', 'Client communication'],
    personName: 'Carlos Rodriguez',
    personId: 'p3',
    reportsToId: '1',
    gwcGetsIt: true,
    gwcWantsIt: true,
    gwcCapacity: true,
    isRightPersonRightSeat: true,
  },
  {
    id: '4',
    seatName: 'Crew Leader - Team B',
    roleDescription: 'Leads painting crew, ensures quality and timeline',
    responsibilities: ['Job site management', 'Quality control', 'Crew supervision', 'Material management', 'Client communication'],
    personName: 'Miguel Santos',
    personId: 'p4',
    reportsToId: '1',
    gwcGetsIt: true,
    gwcWantsIt: true,
    gwcCapacity: false,
    isRightPersonRightSeat: false,
  },
  {
    id: '5',
    seatName: 'Painter - Team A',
    roleDescription: 'Skilled painter, executes painting work',
    responsibilities: ['Surface preparation', 'Paint application', 'Clean-up', 'Tool maintenance', 'Follow safety protocols'],
    personName: 'Jose Martinez',
    personId: 'p5',
    reportsToId: '3',
    gwcGetsIt: true,
    gwcWantsIt: true,
    gwcCapacity: true,
    isRightPersonRightSeat: true,
  },
];

// Meetings
export const mockMeetings: Meeting[] = [
  {
    id: '1',
    meetingDate: '2024-12-12',
    meetingType: 'l10',
    attendees: ['Rodrigo Campos', 'Maria Garcia', 'Carlos Rodriguez', 'Miguel Santos'],
    ratingAvg: 8.5,
    segueNotes: 'Carlos shared that the Davis job is going well. Maria landed a referral from past client.',
    headlines: 'New lead from Greenwich realtor. Positive Google review from Thompson.',
  },
  {
    id: '2',
    meetingDate: '2024-12-05',
    meetingType: 'l10',
    attendees: ['Rodrigo Campos', 'Maria Garcia', 'Carlos Rodriguez', 'Miguel Santos'],
    ratingAvg: 7.8,
    segueNotes: 'Miguel completed training on new spray equipment.',
    headlines: 'Supplier price increase announced.',
  },
  {
    id: '3',
    meetingDate: '2024-11-28',
    meetingType: 'l10',
    attendees: ['Rodrigo Campos', 'Maria Garcia', 'Carlos Rodriguez'],
    ratingAvg: 8.2,
    segueNotes: 'Strong week for leads. Carlos crew finished Anderson job early.',
    headlines: 'Holiday schedule confirmed. Q4 revenue on track.',
  },
];

// Dashboard KPIs
export const mockDashboardKPIs: DashboardKPIs = {
  revenueYTD: 3850000,
  grossMarginPct: 40.2,
  netMarginPct: 18.5,
  jobsCount: 412,
  avgJobSize: 9345,
  avgGpPerJob: 3757,
  avgDaysToCollect: 5.2,
  flaggedJobsCount: 3,
  leadsYTD: 1250,
  closeRate: 42,
};

// Monthly KPIs
export const mockMonthlyKPIs: MonthlyKPI[] = [
  { month: 'Jan', leads: 85, estimatesSent: 52, jobsInvoiced: 28, closeRate: 54, revenue: 245000, grossProfit: 98000, grossMarginPct: 40, netProfit: 45000 },
  { month: 'Feb', leads: 78, estimatesSent: 48, jobsInvoiced: 25, closeRate: 52, revenue: 228000, grossProfit: 91200, grossMarginPct: 40, netProfit: 41000 },
  { month: 'Mar', leads: 95, estimatesSent: 58, jobsInvoiced: 32, closeRate: 55, revenue: 312000, grossProfit: 124800, grossMarginPct: 40, netProfit: 62000 },
  { month: 'Apr', leads: 110, estimatesSent: 68, jobsInvoiced: 38, closeRate: 56, revenue: 368000, grossProfit: 147200, grossMarginPct: 40, netProfit: 75000 },
  { month: 'May', leads: 125, estimatesSent: 78, jobsInvoiced: 45, closeRate: 58, revenue: 425000, grossProfit: 170000, grossMarginPct: 40, netProfit: 89000 },
  { month: 'Jun', leads: 135, estimatesSent: 85, jobsInvoiced: 48, closeRate: 56, revenue: 458000, grossProfit: 183200, grossMarginPct: 40, netProfit: 95000 },
  { month: 'Jul', leads: 128, estimatesSent: 80, jobsInvoiced: 44, closeRate: 55, revenue: 412000, grossProfit: 164800, grossMarginPct: 40, netProfit: 82000 },
  { month: 'Aug', leads: 118, estimatesSent: 72, jobsInvoiced: 40, closeRate: 56, revenue: 385000, grossProfit: 154000, grossMarginPct: 40, netProfit: 76000 },
  { month: 'Sep', leads: 105, estimatesSent: 65, jobsInvoiced: 36, closeRate: 55, revenue: 342000, grossProfit: 136800, grossMarginPct: 40, netProfit: 68000 },
  { month: 'Oct', leads: 112, estimatesSent: 70, jobsInvoiced: 38, closeRate: 54, revenue: 365000, grossProfit: 146000, grossMarginPct: 40, netProfit: 72000 },
  { month: 'Nov', leads: 88, estimatesSent: 55, jobsInvoiced: 28, closeRate: 51, revenue: 275000, grossProfit: 110000, grossMarginPct: 40, netProfit: 52000 },
  { month: 'Dec', leads: 71, estimatesSent: 45, jobsInvoiced: 10, closeRate: 45, revenue: 112000, grossProfit: 44800, grossMarginPct: 40, netProfit: 18000 },
];

// Estimates
export const mockEstimates: Estimate[] = [
  {
    id: '1',
    estimateNumber: 'EST-2024-089',
    leadId: '1',
    clientName: 'John Smith',
    address: '123 Oak Street, Greenwich, CT',
    status: 'sent',
    estimateDate: '2024-12-12',
    validUntil: '2024-12-26',
    lineItems: [
      { id: '1', description: 'Master Bedroom - Walls + Trim + Ceiling', location: 'Master Bedroom', scope: 'walls_trim_ceiling', quantity: 1, unitPrice: 3000, lineTotal: 3000 },
      { id: '2', description: 'Bedroom 2 - Walls + Trim', location: 'Bedroom 2', scope: 'walls_trim', quantity: 1, unitPrice: 1200, lineTotal: 1200 },
      { id: '3', description: 'Bedroom 3 - Walls + Trim', location: 'Bedroom 3', scope: 'walls_trim', quantity: 1, unitPrice: 1200, lineTotal: 1200 },
      { id: '4', description: 'Hallway - Walls + Trim + Ceiling', location: 'Upstairs Hallway', scope: 'walls_trim_ceiling', quantity: 1, unitPrice: 1150, lineTotal: 1150 },
      { id: '5', description: 'Walk-in Closet - Walls + Trim', location: 'Master Closet', quantity: 1, unitPrice: 450, lineTotal: 450 },
      { id: '6', description: 'Doors - Both Sides', location: 'Various', quantity: 8, unitPrice: 125, lineTotal: 1000 },
    ],
    subtotal: 8000,
    discountAmount: 0,
    totalPrice: 8000,
    subMaterialsCost: 1200,
    subLaborCost: 3600,
    subTotalCost: 4800,
    grossProfit: 3200,
    grossMarginPct: 40,
    meetsMinGp: true,
    meetsTargetGm: true,
  },
  {
    id: '2',
    estimateNumber: 'EST-2024-090',
    leadId: '3',
    clientName: 'Michael Brown',
    address: '789 Elm Road, Norwalk, CT',
    status: 'draft',
    estimateDate: '2024-12-14',
    validUntil: '2024-12-28',
    lineItems: [
      { id: '1', description: 'Living Room - Walls Only', location: 'Living Room', scope: 'walls_only', quantity: 1, unitPrice: 1600, lineTotal: 1600 },
      { id: '2', description: 'Dining Room - Walls Only', location: 'Dining Room', scope: 'walls_only', quantity: 1, unitPrice: 950, lineTotal: 950 },
      { id: '3', description: 'Kitchen - Walls Only', location: 'Kitchen', scope: 'walls_only', quantity: 1, unitPrice: 1000, lineTotal: 1000 },
      { id: '4', description: 'Powder Room - Full Refresh', location: 'Powder Room', scope: 'full_refresh', quantity: 1, unitPrice: 950, lineTotal: 950 },
    ],
    subtotal: 4500,
    discountAmount: 0,
    totalPrice: 4500,
    subMaterialsCost: 675,
    subLaborCost: 2025,
    subTotalCost: 2700,
    grossProfit: 1800,
    grossMarginPct: 40,
    meetsMinGp: true,
    meetsTargetGm: true,
  },
];
